default_platform(:ios)

platform :ios do

  lane :register_app do
    produce(app_name: "ithreeHelloWorld")
  end

  lane :create_development_cert do
    cert(development: true)
  end

  lane :get_development_provisioning_profile do
    sigh(development: true)
  end

  lane :get_dev_certs do
    create_development_cert
    get_development_provisioning_profile
  end
end
