default_platform(:ios)

platform :ios do

  lane :register_app do
    produce(app_name: "ithreeHelloWorld")
  end

  lane :create_development_cert do
    cert(development: true)
  end

  lane :get_development_provisioning_profile do
    sigh(development: true)
  end

  lane :get_dev_certs do
    create_development_cert
    get_development_provisioning_profile
  end

  lane :sync_all_development do
    match(type: "development")
  end

  lane :sync_device_info do
    register_devices(
      devices:{
        "ithree iPhone XS" => "UUID"
      }
    )
  end

  lane :bootstrap_code_signing do
    sync_device_info
    match(type: "development")
    match(type: "adhoc")
    match(type: "appstore")
  end
end
