default_platform(:ios)

platform :ios do

  lane :register_app do
    produce(
      username: "APPLE_ID",
      app_identifier: "com.ithree1113.HelloWorld", # Bundle ID
      app_name: "ithreeHelloWorld",
      team_name: "THE_NAME_OF_YOUR_DEVELOPER_PORTAL_TEAM",
      itc_team_name: "THE_NAME_OF_YOUR_APP_STORE_CONNECT_TEAM"
    )
  end

  lane :create_development_cert do
    cert(
      username: "APPLE_ID",
      team_name: "THE_NAME_OF_YOUR_DEVELOPER_PORTAL_TEAM",
      development: true
    )
  end
end
